### PR TITLE
Fixed [PH] Issue

### PR DESCRIPTION
**Pull request by SirCumz**

### CODE REVIEW

**Comment by macdja38** [comment]
Any idea what's going on here? https://pvpcraft.ca/i/tufvt.png

**Comment by SirCumz** [comment]
Well the Name of that node is Empty and removed from the JSON file

**Comment by macdja38** [comment]
Ok, but it still exists as a node, the name should just be "" or null

**Comment by SirCumz** [comment]
you are looking at the wrong file! you should look at the files changed, it's red because it has been removed from the json file

**Comment by macdja38** [comment]
@SirCumz that... would be the problem... we want all the data available, just because something does not have a name does not mean it should be discluded. The json / yaml files are meant to be a json / yaml representation of the files... not a cherry picked set of stuff.

**Comment by SirCumz** [comment]
The current parser excludes empty names to, look at the source. i did not cherry picked anything, my script does exactly the same as what was accepted before, but with the fixes.

**Comment by macdja38** [comment]
@SirCumz I get that, but what happened to these event nodes? I get that they may not have names, but the rest of the data should still be present? https://pvpcraft.ca/i/j7m6t.png

**Pull request closed without merging**
